Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,17 +2,20 @@ name: Deploy PAM
 
 on:
   push:
-    branches: [ master ]
-    paths:
-      - 'LandingPage/**'
-      - 'JavaScript-Playground/**'
+    branches:
+      - master
+  pull_request:
+    branches:
+      - master
 
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
+      # Checkout del repositorio principal (PAM)
     - uses: actions/checkout@v3
-
+    
+      # Checkout del repositorio a81Biz/LandingPage
     - name: Checkout LandingPage
       uses: actions/checkout@v3
       with:
@@ -20,6 +23,7 @@ jobs:
         path: LandingPage
         ref: master
 
+      # Checkout del repositorio a81Biz/JavaScript-Playground
     - name: Checkout JavaScript-Playground
       uses: actions/checkout@v3
       with:
@@ -27,15 +31,41 @@ jobs:
         path: JavaScript-Playground
         ref: main
 
-    - name: Install dependencies
-      run: npm install gh-pages --save-dev
-      run: npm install
-    - name: Build
-      run: npm run deploy
+      # Copiar el contenido del repositorio LandingPage al directorio de despliegue
+    - name: Copy LandingPage Content
+      run: |
+        mkdir -p build/LandingPage
+        cp -R LandingPage/* build/LandingPage/
 
+      # Copiar el contenido del repositorio JavaScript-Playground al directorio de despliegue
+    - name: Copy JavaScript-Playground Content
+      run: |
+        mkdir -p build/JavaScript-Playground
+        cp -R JavaScript-Playground/* build/JavaScript-Playground/
+
+      # Instalar dependencias del proyecto principal (PAM) y construirlo
+    - name: Install dependencies
+      run: npm install
+
+    - name: Build
+      run: npm run build
+
+      # Verificar si la carpeta build fue creada correctamente
+    - name: Check Build Directory
+      run: |
+        if [ ! -d "build" ]; then
+          echo "Error: Build directory not found."
+          exit 1
+        fi
+
+      # Añadir un archivo .nojekyll para evitar conflictos con GitHub Pages
+    - name: Add .nojekyll file
+      run: echo "" > build/.nojekyll
+
+      # Desplegar el contenido a GitHub Pages desde la carpeta build
     - name: Deploy to GitHub Pages
       uses: JamesIves/github-pages-deploy-action@v4
       with:
         github_token: ${{ secrets.PAM_TOKEN }}
         branch: gh-pages
-        folder: build 
+        folder: build
